"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-09-22 14:48:51.765739+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('admin', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('population_source', sa.String(length=255), nullable=True),
    sa.Column('registry_version', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_country'), 'cities', ['country'], unique=False)
    op.create_index('ix_cities_country_region', 'cities', ['country', 'region'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data_tier', sa.String(length=16), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cities_total', sa.Integer(), nullable=False),
    sa.Column('cities_with_data', sa.Integer(), nullable=False),
    sa.Column('cities_missing', sa.Integer(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('events_total', sa.Integer(), nullable=False),
    sa.Column('events_published', sa.Integer(), nullable=False),
    sa.Column('events_excluded', sa.Integer(), nullable=False),
    sa.Column('provider_requests', sa.Integer(), nullable=False),
    sa.Column('provider_errors', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('llm_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_estimated_usd', sa.Float(), nullable=False),
    sa.Column('llm_budget_exhausted', sa.Boolean(), nullable=False),
    sa.Column('methodology_version', sa.String(length=16), nullable=False),
    sa.Column('registry_version', sa.String(length=32), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_date_status', 'pipeline_runs', ['analysis_date', 'status'], unique=False)
    op.create_index('ix_runs_kind_started', 'pipeline_runs', ['kind', 'started_at'], unique=False)
    op.create_index('ix_runs_published', 'pipeline_runs', ['published', 'analysis_date'], unique=False)
    op.create_table('anomaly_events',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('city_id', sa.String(length=64), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('baseline_mean', sa.Float(), nullable=True),
    sa.Column('baseline_median', sa.Float(), nullable=True),
    sa.Column('baseline_std', sa.Float(), nullable=True),
    sa.Column('baseline_p25', sa.Float(), nullable=True),
    sa.Column('baseline_p75', sa.Float(), nullable=True),
    sa.Column('baseline_min', sa.Float(), nullable=True),
    sa.Column('baseline_max', sa.Float(), nullable=True),
    sa.Column('baseline_n', sa.Integer(), nullable=False),
    sa.Column('baseline_sufficient', sa.Boolean(), nullable=False),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('robust_deviation', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('z_valid', sa.Boolean(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('tail_probability', sa.Float(), nullable=True),
    sa.Column('return_period_years', sa.Float(), nullable=True),
    sa.Column('tail_probability_is_bounded', sa.Boolean(), nullable=False),
    sa.Column('beyond_baseline_sample', sa.Boolean(), nullable=False),
    sa.Column('surprisal', sa.Float(), nullable=False),
    sa.Column('margin_bonus', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('data_tier', sa.String(length=16), nullable=False),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('source_dataset', sa.String(length=64), nullable=False),
    sa.Column('observation_type', sa.String(length=32), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('excluded_reason', sa.String(length=128), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('methodology_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_city_metric_date', 'anomaly_events', ['city_id', 'metric', 'local_date'], unique=False)
    op.create_index('ix_events_date_score', 'anomaly_events', ['local_date', 'anomaly_score'], unique=False)
    op.create_index('ix_events_run', 'anomaly_events', ['run_id'], unique=False)
    op.create_table('baseline_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.String(length=64), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('day_of_year', sa.Integer(), nullable=False),
    sa.Column('reference_start_year', sa.Integer(), nullable=False),
    sa.Column('reference_end_year', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('n_years', sa.Integer(), nullable=False),
    sa.Column('sufficient', sa.Boolean(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('median', sa.Float(), nullable=True),
    sa.Column('p25', sa.Float(), nullable=True),
    sa.Column('p75', sa.Float(), nullable=True),
    sa.Column('iqr', sa.Float(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('quantiles', sa.JSON(), nullable=True),
    sa.Column('low_order_stats', sa.JSON(), nullable=True),
    sa.Column('high_order_stats', sa.JSON(), nullable=True),
    sa.Column('histogram', sa.JSON(), nullable=True),
    sa.Column('zero_fraction', sa.Float(), nullable=True),
    sa.Column('nonzero_n', sa.Integer(), nullable=True),
    sa.Column('nonzero_quantiles', sa.JSON(), nullable=True),
    sa.Column('source_dataset', sa.String(length=64), nullable=False),
    sa.Column('methodology_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'metric', 'day_of_year', 'reference_start_year', 'reference_end_year', 'window_days', 'methodology_version', name='uq_baseline_identity')
    )
    op.create_index('ix_baseline_lookup', 'baseline_statistics', ['city_id', 'metric', 'day_of_year'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.String(length=64), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('temp_max_c', sa.Float(), nullable=True),
    sa.Column('temp_min_c', sa.Float(), nullable=True),
    sa.Column('temp_mean_c', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('wind_gust_max_kmh', sa.Float(), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('source_dataset', sa.String(length=64), nullable=False),
    sa.Column('source_endpoint', sa.String(length=255), nullable=True),
    sa.Column('observation_type', sa.String(length=32), nullable=False),
    sa.Column('grid_latitude', sa.Float(), nullable=True),
    sa.Column('grid_longitude', sa.Float(), nullable=True),
    sa.Column('grid_elevation_m', sa.Float(), nullable=True),
    sa.Column('data_tier', sa.String(length=16), nullable=False),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('units', sa.JSON(), nullable=True),
    sa.Column('utc_offset_seconds', sa.Integer(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'local_date', 'source_dataset', name='uq_obs_city_date_dataset')
    )
    op.create_index('ix_obs_city_date', 'weather_observations', ['city_id', 'local_date'], unique=False)
    op.create_index('ix_obs_date_tier', 'weather_observations', ['local_date', 'data_tier'], unique=False)
    op.create_index('ix_obs_local_date', 'weather_observations', ['local_date'], unique=False)
    op.create_table('agent_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=160), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('statistical_explanation', sa.Text(), nullable=False),
    sa.Column('historical_context', sa.Text(), nullable=False),
    sa.Column('caveats', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('generator', sa.String(length=16), nullable=False),
    sa.Column('llm_provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('fallback_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['anomaly_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'run_id', name='uq_explanation_event_run')
    )
    op.create_index('ix_explanations_event', 'agent_explanations', ['event_id'], unique=False)
    op.create_table('daily_rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=160), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('methodology_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['anomaly_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'event_id', name='uq_ranking_run_event'),
    sa.UniqueConstraint('run_id', 'rank', name='uq_ranking_run_rank')
    )
    op.create_index('ix_rankings_date_rank', 'daily_rankings', ['analysis_date', 'rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rankings_date_rank', table_name='daily_rankings')
    op.drop_table('daily_rankings')
    op.drop_index('ix_explanations_event', table_name='agent_explanations')
    op.drop_table('agent_explanations')
    op.drop_index('ix_obs_local_date', table_name='weather_observations')
    op.drop_index('ix_obs_date_tier', table_name='weather_observations')
    op.drop_index('ix_obs_city_date', table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index('ix_baseline_lookup', table_name='baseline_statistics')
    op.drop_table('baseline_statistics')
    op.drop_index('ix_events_run', table_name='anomaly_events')
    op.drop_index('ix_events_date_score', table_name='anomaly_events')
    op.drop_index('ix_events_city_metric_date', table_name='anomaly_events')
    op.drop_table('anomaly_events')
    op.drop_index('ix_runs_published', table_name='pipeline_runs')
    op.drop_index('ix_runs_kind_started', table_name='pipeline_runs')
    op.drop_index('ix_runs_date_status', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_cities_country_region', table_name='cities')
    op.drop_index(op.f('ix_cities_country'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
